mod emitters;
mod stdin;
mod widget_ops;
mod window_ops;

use std::collections::HashMap;
use std::sync::Mutex;

use iced::widget::{container, pane_grid, text};
use iced::{Element, Fill, Point, Subscription, Task, Theme, event, system, window};

use julep_core::codec::Codec;
use julep_core::extensions::{EventResult, ExtensionDispatcher};
use julep_core::message::{
    KeyEventData, Message, StdinEvent, serialize_modifiers, serialize_mouse_button,
    serialize_scroll_delta,
};
use julep_core::protocol::{IncomingMessage, OutgoingEvent};

pub(crate) use emitters::emit_hello;
use emitters::emit_screenshot_response;
use emitters::{emit_effect_response, emit_event, message_to_event};
use stdin::{STDIN_RX, read_initial_settings, spawn_stdin_reader, stdin_subscription};

// ---------------------------------------------------------------------------
// App state
// ---------------------------------------------------------------------------

struct App {
    core: julep_core::engine::Core,
    theme: Theme,
    /// Tasks generated by apply() that must be returned from update().
    /// Widget ops (focus, scroll, close_window) produce iced Tasks, but
    /// apply() doesn't return them. They accumulate here and are drained
    /// via Task::batch in the Tick handler.
    pending_tasks: Vec<Task<Message>>,
    /// Julep window ID -> iced window ID.
    window_map: HashMap<String, window::Id>,
    /// Iced window ID -> julep window ID.
    reverse_window_map: HashMap<window::Id, String>,
    /// When true, handle Query/Interact/SnapshotCapture/ScreenshotCapture/Reset on stdin.
    test_mode: bool,
    /// In-memory image handles for use by Image widgets and canvas draw.
    image_registry: julep_core::image_registry::ImageRegistry,
    /// Current system theme, tracked via ThemeChanged subscription.
    /// Used when a window or app theme is set to "system".
    system_theme: Theme,
    /// True when the app-level theme is "system" (follow OS preference).
    theme_follows_system: bool,
    /// Global scale factor multiplier (1.0 = follow OS DPI).
    scale_factor: f32,
    /// Last slider value per widget ID, for correct on_release events.
    last_slide_values: HashMap<String, f64>,
    /// Extension dispatcher for custom widget types.
    dispatcher: ExtensionDispatcher,
    /// Per-window resolved theme cache. Populated during apply() when the tree
    /// changes (mutable context), read during theme_for_window() (immutable).
    window_theme_cache: HashMap<String, Theme>,
}

impl App {
    fn new(test_mode: bool, dispatcher: ExtensionDispatcher) -> Self {
        if test_mode {
            log::info!("running in test mode");
        }
        Self {
            core: julep_core::engine::Core::new(),
            theme: Theme::Dark,
            pending_tasks: Vec::new(),
            window_map: HashMap::new(),
            reverse_window_map: HashMap::new(),
            test_mode,
            image_registry: julep_core::image_registry::ImageRegistry::new(),
            system_theme: Theme::Dark,
            theme_follows_system: false,
            scale_factor: 1.0,
            last_slide_values: HashMap::new(),
            dispatcher,
            window_theme_cache: HashMap::new(),
        }
    }

    fn title_for_window(&self, window_id: window::Id) -> String {
        if let Some(julep_id) = self.reverse_window_map.get(&window_id)
            && let Some(node) = self.core.tree.find_window(julep_id)
            && let Some(title) = node.props.get("title").and_then(|v| v.as_str())
        {
            // Strip control characters to prevent injection into
            // window titles / terminal escape sequences.
            return title.chars().filter(|c| !c.is_control()).collect();
        }
        "Julep".to_string()
    }

    fn theme_for_window(&self, window_id: window::Id) -> Theme {
        if let Some(julep_id) = self.reverse_window_map.get(&window_id)
            && let Some(cached) = self.window_theme_cache.get(julep_id)
        {
            return cached.clone();
        }
        if self.theme_follows_system {
            self.system_theme.clone()
        } else {
            self.theme.clone()
        }
    }

    /// Return the scale factor for a window. Per-window overrides take
    /// precedence over the global setting.
    fn scale_factor_for_window(&self, window_id: window::Id) -> f32 {
        let sf = if let Some(julep_id) = self.reverse_window_map.get(&window_id) {
            if let Some(node) = self.core.tree.find_window(julep_id) {
                if let Some(sf) = node.props.get("scale_factor").and_then(|v| v.as_f64()) {
                    sf as f32
                } else {
                    self.scale_factor
                }
            } else {
                self.scale_factor
            }
        } else {
            self.scale_factor
        };
        if sf <= 0.0 || !sf.is_finite() {
            log::warn!("invalid scale_factor {sf}, using 1.0");
            1.0
        } else {
            sf
        }
    }

    /// Emit an event if the given subscription key is registered.
    /// Returns the tag if registered (for callers that need it), None otherwise.
    fn emit_if_subscribed(&self, key: &str, event_fn: impl FnOnce(String) -> OutgoingEvent) {
        if let Some(tag) = self.core.active_subscriptions.get(key) {
            emit_event(event_fn(tag.clone()));
        }
    }

    /// Resolve a julep window ID string from an iced window::Id.
    fn julep_id_for(&self, iced_id: &window::Id) -> String {
        self.reverse_window_map
            .get(iced_id)
            .cloned()
            .unwrap_or_default()
    }

    fn update(&mut self, message: Message) -> Task<Message> {
        match message {
            Message::Stdin(event) => self.handle_stdin(event),
            Message::NoOp => Task::none(),
            // Simple widget events: map through message_to_event and emit.
            ref msg @ (Message::Click(_)
            | Message::Input(..)
            | Message::Submit(..)
            | Message::Toggle(..)
            | Message::Select(..)) => {
                if let Some(event) = message_to_event(msg) {
                    emit_event(event);
                }
                Task::none()
            }
            Message::Slide(ref id, value) => {
                self.last_slide_values.insert(id.clone(), value);
                emit_event(OutgoingEvent::slide(id.clone(), value));
                Task::none()
            }
            Message::SlideRelease(ref id) => {
                let value = self.last_slide_values.remove(id).unwrap_or(0.0);
                emit_event(OutgoingEvent::slide_release(id.clone(), value));
                Task::none()
            }
            // Generic extension-aware events: route through dispatcher first.
            //
            // Redraw contract: iced::daemon rebuilds user interfaces (calls
            // view_window for every open window) and requests a
            // window-level redraw after every update() call, regardless of
            // the Task returned here. Returning Task::none() is therefore
            // correct for all three EventResult variants -- the view IS
            // rebuilt, and any state the extension mutated in
            // ExtensionCaches will be visible to the next render() call.
            //
            // Canvas caching note: if an extension renders via
            // canvas::Cache, the cached geometry is NOT automatically
            // invalidated by a view rebuild. The extension must call
            // cache.clear() itself when its state changes -- typically by
            // using a GenerationCounter (see extensions.rs) bumped in
            // handle_event and checked in Program::draw(). There is no
            // need to emit dummy events or return special Tasks to force a
            // redraw; iced already takes care of the update-view-render
            // cycle.
            Message::Event(ref id, ref data, ref family) => {
                let result =
                    self.dispatcher
                        .handle_event(id, family, data, &mut self.core.caches.extension);
                match result {
                    EventResult::PassThrough => {
                        let data_opt = if data.is_null() {
                            None
                        } else {
                            Some(data.clone())
                        };
                        emit_event(OutgoingEvent::generic(family.clone(), id.clone(), data_opt));
                    }
                    EventResult::Consumed(events) => {
                        for ev in events {
                            emit_event(ev);
                        }
                    }
                    EventResult::Observed(events) => {
                        let data_opt = if data.is_null() {
                            None
                        } else {
                            Some(data.clone())
                        };
                        emit_event(OutgoingEvent::generic(family.clone(), id.clone(), data_opt));
                        for ev in events {
                            emit_event(ev);
                        }
                    }
                }
                Task::none()
            }
            Message::TextEditorAction(id, action) => {
                let is_edit = action.is_edit();
                if let Some(content) = self.core.caches.editor_content_mut(&id) {
                    content.perform(action);
                    if is_edit {
                        let new_text = content.text();
                        emit_event(OutgoingEvent::input(id, new_text));
                    }
                }
                Task::none()
            }
            Message::MarkdownUrl(url) => {
                log::debug!("markdown link clicked: {url}");
                Task::none()
            }

            // -- Keyboard events --
            Message::KeyPressed(data) => self.handle_key_pressed(data),
            Message::KeyReleased(data) => self.handle_key_released(data),
            Message::ModifiersChanged(mods) => self.handle_modifiers_changed(mods),

            // -- Mouse events --
            Message::CursorMoved(pos, _win) => self.handle_cursor_moved(pos),
            Message::CursorEntered(_win) => self.handle_cursor_entered(),
            Message::CursorLeft(_win) => self.handle_cursor_left(),
            Message::MouseButtonPressed(button, _win) => self.handle_mouse_button_pressed(button),
            Message::MouseButtonReleased(button, _win) => self.handle_mouse_button_released(button),
            Message::WheelScrolled(delta, _win) => self.handle_wheel_scrolled(delta),

            // -- Touch events --
            Message::FingerPressed(finger, pos, _win) => self.handle_finger_pressed(finger, pos),
            Message::FingerMoved(finger, pos, _win) => self.handle_finger_moved(finger, pos),
            Message::FingerLifted(finger, pos, _win) => self.handle_finger_lifted(finger, pos),
            Message::FingerLost(finger, pos, _win) => self.handle_finger_lost(finger, pos),

            // -- IME events --
            Message::ImeOpened => self.handle_ime_opened(),
            Message::ImePreedit(text, cursor) => self.handle_ime_preedit(text, cursor),
            Message::ImeCommit(text) => self.handle_ime_commit(text),
            Message::ImeClosed => self.handle_ime_closed(),

            // -- Window lifecycle events --
            Message::WindowCloseRequested(window_id) => {
                if let Some(tag) = self.core.active_subscriptions.get("on_window_close") {
                    let julep_id = self.julep_id_for(&window_id);
                    emit_event(OutgoingEvent::window_close_requested(tag.clone(), julep_id));
                }
                // Do NOT close the window or remove from maps here. The host
                // decides whether to close by sending a close_window command
                // or removing the window from the tree. Closing immediately
                // would bypass app-level confirmation dialogs.
                Task::none()
            }
            Message::WindowClosed(window_id) => {
                if let Some(julep_id) = self.reverse_window_map.remove(&window_id) {
                    self.window_map.remove(&julep_id);
                    if let Some(tag) = self.core.active_subscriptions.get("on_window_event") {
                        emit_event(OutgoingEvent::window_closed(tag.clone(), julep_id.clone()));
                    }
                    log::info!("window closed: {julep_id}");
                }
                // All managed windows gone -- notify the host.
                // The host can choose to exit, send a new Snapshot, or take other action.
                // We do NOT call iced::exit() here because the daemon should stay alive
                // to receive new tree snapshots (e.g. after a Reset or window re-creation).
                if self.window_map.is_empty() && self.core.tree.root().is_some() {
                    log::info!("all windows closed -- notifying host");
                    emit_event(OutgoingEvent::generic(
                        "all_windows_closed".to_string(),
                        String::new(),
                        None,
                    ));
                }
                Task::none()
            }
            Message::WindowOpened(iced_id, julep_id) => {
                log::info!("window opened: {julep_id} -> {iced_id:?}");
                self.window_map.insert(julep_id.clone(), iced_id);
                self.reverse_window_map.insert(iced_id, julep_id);
                Task::none()
            }
            Message::WindowEvent(iced_id, evt) => self.handle_window_event(iced_id, evt),

            // -- System / animation --
            Message::AnimationFrame(instant) => {
                if let Some(tag) = self.core.active_subscriptions.get("on_animation_frame") {
                    // Convert Instant to a duration since some epoch. We use
                    // elapsed from the process start as a monotonic timestamp.
                    let millis = instant
                        .duration_since(iced::time::Instant::now() - instant.elapsed())
                        .as_millis();
                    emit_event(OutgoingEvent::animation_frame(tag.clone(), millis));
                }
                Task::none()
            }
            Message::ThemeChanged(mode) => {
                // Track system theme so "system" theme value follows OS preference
                self.system_theme = match mode {
                    iced::theme::Mode::Light => Theme::Light,
                    iced::theme::Mode::Dark => Theme::Dark,
                    _ => Theme::Dark,
                };
                if let Some(tag) = self.core.active_subscriptions.get("on_theme_change") {
                    let mode_str = match mode {
                        iced::theme::Mode::Light => "light",
                        iced::theme::Mode::Dark => "dark",
                        _ => "system",
                    };
                    emit_event(OutgoingEvent::theme_changed(
                        tag.clone(),
                        mode_str.to_string(),
                    ));
                }
                Task::none()
            }
            Message::SensorResize(id, width, height) => {
                emit_event(OutgoingEvent::sensor_resize(id, width, height));
                Task::none()
            }
            Message::CanvasEvent(id, kind, x, y, extra) => {
                match kind.as_str() {
                    "press" => emit_event(OutgoingEvent::canvas_press(id, x, y, extra)),
                    "release" => emit_event(OutgoingEvent::canvas_release(id, x, y, extra)),
                    "move" => emit_event(OutgoingEvent::canvas_move(id, x, y)),
                    _ => {}
                }
                Task::none()
            }
            Message::CanvasScroll(id, cx, cy, dx, dy) => {
                emit_event(OutgoingEvent::canvas_scroll(id, cx, cy, dx, dy));
                Task::none()
            }
            Message::PaneResized(grid_id, evt) => self.handle_pane_resized(grid_id, evt),
            Message::PaneDragged(grid_id, evt) => self.handle_pane_dragged(grid_id, evt),
            Message::PaneClicked(grid_id, pane) => self.handle_pane_clicked(grid_id, pane),
            Message::ScrollEvent(
                id,
                abs_x,
                abs_y,
                rel_x,
                rel_y,
                bounds_w,
                bounds_h,
                content_w,
                content_h,
            ) => {
                emit_event(OutgoingEvent::scroll(
                    id, abs_x, abs_y, rel_x, rel_y, bounds_w, bounds_h, content_w, content_h,
                ));
                Task::none()
            }
            Message::Paste(id, text) => {
                emit_event(OutgoingEvent::paste(id, text));
                Task::none()
            }
            Message::OptionHovered(id, value) => {
                emit_event(OutgoingEvent::option_hovered(id, value));
                Task::none()
            }
            Message::MouseAreaEvent(id, kind) => {
                let event = match kind.as_str() {
                    "right_press" => OutgoingEvent::mouse_right_press(id),
                    "right_release" => OutgoingEvent::mouse_right_release(id),
                    "middle_press" => OutgoingEvent::mouse_middle_press(id),
                    "middle_release" => OutgoingEvent::mouse_middle_release(id),
                    "double_click" => OutgoingEvent::mouse_double_click(id),
                    "enter" => OutgoingEvent::mouse_enter(id),
                    "exit" => OutgoingEvent::mouse_exit(id),
                    _ => return Task::none(),
                };
                emit_event(event);
                Task::none()
            }
            Message::MouseAreaMove(id, x, y) => {
                emit_event(OutgoingEvent::mouse_area_move(id, x, y));
                Task::none()
            }
            Message::MouseAreaScroll(id, dx, dy) => {
                emit_event(OutgoingEvent::mouse_area_scroll(id, dx, dy));
                Task::none()
            }
        }
    }

    // -----------------------------------------------------------------------
    // Extracted sub-dispatch methods for update()
    // -----------------------------------------------------------------------

    fn handle_stdin(&mut self, event: StdinEvent) -> Task<Message> {
        match event {
            StdinEvent::Message(incoming) => {
                // In test mode, handle test-specific messages directly
                // instead of passing them to Core::apply.
                if self.test_mode && crate::test_mode::test_helpers::is_test_message(&incoming) {
                    match incoming {
                        IncomingMessage::Query {
                            id,
                            target,
                            selector,
                        } => {
                            crate::test_protocol::handle_query(&self.core, id, target, selector);
                            return Task::none();
                        }
                        IncomingMessage::Interact {
                            id,
                            action,
                            selector,
                            payload,
                        } => {
                            crate::test_protocol::handle_interact(
                                &self.core, id, action, selector, payload,
                            );
                            return Task::none();
                        }
                        IncomingMessage::Reset { id } => {
                            // Clean up extension state before wiping core.
                            self.dispatcher.reset(&mut self.core.caches.extension);

                            // Reset core and emit the response.
                            crate::test_protocol::handle_reset(&mut self.core, id);

                            // Close all open windows and clear maps.
                            let close_tasks: Vec<Task<Message>> = self
                                .window_map
                                .values()
                                .map(|&iced_id| window::close(iced_id))
                                .collect();
                            self.window_map.clear();
                            self.reverse_window_map.clear();

                            // Reset remaining App-level state.
                            self.image_registry = julep_core::image_registry::ImageRegistry::new();
                            self.theme = Theme::Dark;
                            self.theme_follows_system = false;
                            self.scale_factor = 1.0;
                            self.last_slide_values.clear();
                            self.pending_tasks.clear();
                            self.window_theme_cache.clear();

                            return Task::batch(close_tasks);
                        }
                        IncomingMessage::SnapshotCapture { id, name, .. } => {
                            crate::test_protocol::handle_snapshot_capture(&self.core, id, name);
                            return Task::none();
                        }
                        IncomingMessage::ScreenshotCapture { id, name, .. } => {
                            // Capture real GPU-rendered pixels via iced
                            if let Some((_, &iced_id)) = self.window_map.iter().next() {
                                return window::screenshot(iced_id).map(move |shot| {
                                    use sha2::{Digest, Sha256};
                                    let rgba: &[u8] = &shot.rgba;
                                    let mut hasher = Sha256::new();
                                    hasher.update(rgba);
                                    let hash = format!("{:x}", hasher.finalize());
                                    let w = shot.size.width;
                                    let h = shot.size.height;
                                    emit_screenshot_response(&id, &name, &hash, w, h, rgba);
                                    Message::NoOp
                                });
                            }
                            // No windows open -- return empty screenshot
                            emit_screenshot_response(&id, &name, "", 0, 0, &[]);
                            return Task::none();
                        }
                        _ => return Task::none(),
                    }
                }
                self.apply(incoming);
                let tasks: Vec<Task<Message>> = self.pending_tasks.drain(..).collect();
                Task::batch(tasks)
            }
            StdinEvent::Warning(msg) => {
                log::warn!("stdin warning: {msg}");
                Task::none()
            }
            StdinEvent::Closed => {
                log::info!("stdin closed -- exiting");
                iced::exit()
            }
        }
    }

    fn handle_key_pressed(&self, data: KeyEventData) -> Task<Message> {
        let tag = self
            .core
            .active_subscriptions
            .get("on_key_press")
            .or_else(|| self.core.active_subscriptions.get("on_event"));
        if let Some(tag) = tag {
            emit_event(OutgoingEvent::key_press(tag.clone(), &data));
        }
        Task::none()
    }

    fn handle_key_released(&self, data: KeyEventData) -> Task<Message> {
        let tag = self
            .core
            .active_subscriptions
            .get("on_key_release")
            .or_else(|| self.core.active_subscriptions.get("on_event"));
        if let Some(tag) = tag {
            emit_event(OutgoingEvent::key_release(tag.clone(), &data));
        }
        Task::none()
    }

    fn handle_modifiers_changed(&self, mods: iced::keyboard::Modifiers) -> Task<Message> {
        let tag = self
            .core
            .active_subscriptions
            .get("on_modifiers_changed")
            .or_else(|| self.core.active_subscriptions.get("on_event"));
        if let Some(tag) = tag {
            emit_event(OutgoingEvent::modifiers_changed(
                tag.clone(),
                serialize_modifiers(mods),
            ));
        }
        Task::none()
    }

    fn handle_cursor_moved(&self, pos: Point) -> Task<Message> {
        let tag = self
            .core
            .active_subscriptions
            .get("on_mouse_move")
            .or_else(|| self.core.active_subscriptions.get("on_event"));
        if let Some(tag) = tag {
            emit_event(OutgoingEvent::cursor_moved(tag.clone(), pos.x, pos.y));
        }
        Task::none()
    }

    fn handle_cursor_entered(&self) -> Task<Message> {
        let tag = self
            .core
            .active_subscriptions
            .get("on_mouse_move")
            .or_else(|| self.core.active_subscriptions.get("on_event"));
        if let Some(tag) = tag {
            emit_event(OutgoingEvent::cursor_entered(tag.clone()));
        }
        Task::none()
    }

    fn handle_cursor_left(&self) -> Task<Message> {
        let tag = self
            .core
            .active_subscriptions
            .get("on_mouse_move")
            .or_else(|| self.core.active_subscriptions.get("on_event"));
        if let Some(tag) = tag {
            emit_event(OutgoingEvent::cursor_left(tag.clone()));
        }
        Task::none()
    }

    fn handle_mouse_button_pressed(&self, button: iced::mouse::Button) -> Task<Message> {
        let tag = self
            .core
            .active_subscriptions
            .get("on_mouse_button")
            .or_else(|| self.core.active_subscriptions.get("on_event"));
        if let Some(tag) = tag {
            emit_event(OutgoingEvent::button_pressed(
                tag.clone(),
                serialize_mouse_button(&button),
            ));
        }
        Task::none()
    }

    fn handle_mouse_button_released(&self, button: iced::mouse::Button) -> Task<Message> {
        let tag = self
            .core
            .active_subscriptions
            .get("on_mouse_button")
            .or_else(|| self.core.active_subscriptions.get("on_event"));
        if let Some(tag) = tag {
            emit_event(OutgoingEvent::button_released(
                tag.clone(),
                serialize_mouse_button(&button),
            ));
        }
        Task::none()
    }

    fn handle_wheel_scrolled(&self, delta: iced::mouse::ScrollDelta) -> Task<Message> {
        let tag = self
            .core
            .active_subscriptions
            .get("on_mouse_scroll")
            .or_else(|| self.core.active_subscriptions.get("on_event"));
        if let Some(tag) = tag {
            let (dx, dy, unit) = serialize_scroll_delta(&delta);
            emit_event(OutgoingEvent::wheel_scrolled(tag.clone(), dx, dy, unit));
        }
        Task::none()
    }

    fn handle_finger_pressed(&self, finger: iced::touch::Finger, pos: Point) -> Task<Message> {
        let tag = self
            .core
            .active_subscriptions
            .get("on_touch")
            .or_else(|| self.core.active_subscriptions.get("on_event"));
        if let Some(tag) = tag {
            emit_event(OutgoingEvent::finger_pressed(
                tag.clone(),
                finger.0,
                pos.x,
                pos.y,
            ));
        }
        Task::none()
    }

    fn handle_finger_moved(&self, finger: iced::touch::Finger, pos: Point) -> Task<Message> {
        let tag = self
            .core
            .active_subscriptions
            .get("on_touch")
            .or_else(|| self.core.active_subscriptions.get("on_event"));
        if let Some(tag) = tag {
            emit_event(OutgoingEvent::finger_moved(
                tag.clone(),
                finger.0,
                pos.x,
                pos.y,
            ));
        }
        Task::none()
    }

    fn handle_finger_lifted(&self, finger: iced::touch::Finger, pos: Point) -> Task<Message> {
        let tag = self
            .core
            .active_subscriptions
            .get("on_touch")
            .or_else(|| self.core.active_subscriptions.get("on_event"));
        if let Some(tag) = tag {
            emit_event(OutgoingEvent::finger_lifted(
                tag.clone(),
                finger.0,
                pos.x,
                pos.y,
            ));
        }
        Task::none()
    }

    fn handle_finger_lost(&self, finger: iced::touch::Finger, pos: Point) -> Task<Message> {
        let tag = self
            .core
            .active_subscriptions
            .get("on_touch")
            .or_else(|| self.core.active_subscriptions.get("on_event"));
        if let Some(tag) = tag {
            emit_event(OutgoingEvent::finger_lost(
                tag.clone(),
                finger.0,
                pos.x,
                pos.y,
            ));
        }
        Task::none()
    }

    fn handle_ime_opened(&self) -> Task<Message> {
        self.emit_if_subscribed("on_ime", OutgoingEvent::ime_opened);
        Task::none()
    }

    fn handle_ime_preedit(
        &self,
        text: String,
        cursor: Option<std::ops::Range<usize>>,
    ) -> Task<Message> {
        self.emit_if_subscribed("on_ime", |tag| {
            OutgoingEvent::ime_preedit(tag, text, cursor)
        });
        Task::none()
    }

    fn handle_ime_commit(&self, text: String) -> Task<Message> {
        self.emit_if_subscribed("on_ime", |tag| OutgoingEvent::ime_commit(tag, text));
        Task::none()
    }

    fn handle_ime_closed(&self) -> Task<Message> {
        self.emit_if_subscribed("on_ime", OutgoingEvent::ime_closed);
        Task::none()
    }

    fn handle_window_event(&self, iced_id: window::Id, evt: window::Event) -> Task<Message> {
        let julep_id = self.julep_id_for(&iced_id);
        match evt {
            window::Event::Opened { position, size } => {
                if let Some(tag) = self.core.active_subscriptions.get("on_window_event") {
                    let pos = position.map(|p| (p.x, p.y));
                    emit_event(OutgoingEvent::window_opened(
                        tag.clone(),
                        julep_id.clone(),
                        pos,
                        size.width,
                        size.height,
                    ));
                }
                if let Some(tag) = self.core.active_subscriptions.get("on_window_open") {
                    let pos = position.map(|p| (p.x, p.y));
                    emit_event(OutgoingEvent::window_opened(
                        tag.clone(),
                        julep_id,
                        pos,
                        size.width,
                        size.height,
                    ));
                }
            }
            window::Event::Closed => {
                if let Some(tag) = self.core.active_subscriptions.get("on_window_event") {
                    emit_event(OutgoingEvent::window_closed(tag.clone(), julep_id));
                }
            }
            window::Event::Moved(point) => {
                if let Some(tag) = self.core.active_subscriptions.get("on_window_event") {
                    emit_event(OutgoingEvent::window_moved(
                        tag.clone(),
                        julep_id.clone(),
                        point.x,
                        point.y,
                    ));
                }
                if let Some(tag) = self.core.active_subscriptions.get("on_window_move") {
                    emit_event(OutgoingEvent::window_moved(
                        tag.clone(),
                        julep_id,
                        point.x,
                        point.y,
                    ));
                }
            }
            window::Event::Resized(size) => {
                if let Some(tag) = self.core.active_subscriptions.get("on_window_event") {
                    emit_event(OutgoingEvent::window_resized(
                        tag.clone(),
                        julep_id.clone(),
                        size.width,
                        size.height,
                    ));
                }
                if let Some(tag) = self.core.active_subscriptions.get("on_window_resize") {
                    emit_event(OutgoingEvent::window_resized(
                        tag.clone(),
                        julep_id,
                        size.width,
                        size.height,
                    ));
                }
            }
            window::Event::Rescaled(factor) => {
                if let Some(tag) = self.core.active_subscriptions.get("on_window_event") {
                    emit_event(OutgoingEvent::window_rescaled(
                        tag.clone(),
                        julep_id,
                        factor,
                    ));
                }
            }
            window::Event::Focused => {
                if let Some(tag) = self.core.active_subscriptions.get("on_window_event") {
                    emit_event(OutgoingEvent::window_focused(tag.clone(), julep_id.clone()));
                }
                if let Some(tag) = self.core.active_subscriptions.get("on_window_focus") {
                    emit_event(OutgoingEvent::window_focused(tag.clone(), julep_id));
                }
            }
            window::Event::Unfocused => {
                if let Some(tag) = self.core.active_subscriptions.get("on_window_event") {
                    emit_event(OutgoingEvent::window_unfocused(
                        tag.clone(),
                        julep_id.clone(),
                    ));
                }
                if let Some(tag) = self.core.active_subscriptions.get("on_window_unfocus") {
                    emit_event(OutgoingEvent::window_unfocused(tag.clone(), julep_id));
                }
            }
            window::Event::FileHovered(path) => {
                if let Some(tag) = self.core.active_subscriptions.get("on_file_drop") {
                    let path_str = match path.to_str() {
                        Some(s) => s.to_string(),
                        None => {
                            log::warn!(
                                "file path contains non-UTF-8 bytes, using lossy conversion: {}",
                                path.display()
                            );
                            path.to_string_lossy().into_owned()
                        }
                    };
                    emit_event(OutgoingEvent::file_hovered(tag.clone(), julep_id, path_str));
                }
            }
            window::Event::FileDropped(path) => {
                if let Some(tag) = self.core.active_subscriptions.get("on_file_drop") {
                    let path_str = match path.to_str() {
                        Some(s) => s.to_string(),
                        None => {
                            log::warn!(
                                "file path contains non-UTF-8 bytes, using lossy conversion: {}",
                                path.display()
                            );
                            path.to_string_lossy().into_owned()
                        }
                    };
                    emit_event(OutgoingEvent::file_dropped(tag.clone(), julep_id, path_str));
                }
            }
            window::Event::FilesHoveredLeft => {
                if let Some(tag) = self.core.active_subscriptions.get("on_file_drop") {
                    emit_event(OutgoingEvent::files_hovered_left(tag.clone(), julep_id));
                }
            }
            window::Event::CloseRequested => {
                // Handled via close_requests() subscription separately.
            }
            window::Event::RedrawRequested(_) => {
                // Handled via animation_frame subscription separately.
            }
        }
        Task::none()
    }

    fn handle_pane_resized(
        &mut self,
        grid_id: String,
        evt: pane_grid::ResizeEvent,
    ) -> Task<Message> {
        if let Some(state) = self.core.caches.pane_grid_state_mut(&grid_id) {
            state.resize(evt.split, evt.ratio);
        }
        emit_event(OutgoingEvent::pane_resized(
            grid_id,
            format!("{:?}", evt.split),
            evt.ratio,
        ));
        Task::none()
    }

    fn handle_pane_dragged(&mut self, grid_id: String, evt: pane_grid::DragEvent) -> Task<Message> {
        if let pane_grid::DragEvent::Dropped { pane, target } = evt
            && let Some(state) = self.core.caches.pane_grid_state_mut(&grid_id)
        {
            // Look up julep IDs for the panes before swapping
            let pane_id = state.get(pane).cloned().unwrap_or_default();
            let target_pane = match target {
                pane_grid::Target::Edge(_) => "edge".to_string(),
                pane_grid::Target::Pane(p, _) => state.get(p).cloned().unwrap_or_default(),
            };
            state.drop(pane, target);
            emit_event(OutgoingEvent::pane_dragged(grid_id, pane_id, target_pane));
        }
        Task::none()
    }

    fn handle_pane_clicked(&self, grid_id: String, pane: pane_grid::Pane) -> Task<Message> {
        if let Some(state) = self.core.caches.pane_grid_state(&grid_id) {
            let pane_id = state.get(pane).cloned().unwrap_or_default();
            emit_event(OutgoingEvent::pane_clicked(grid_id, pane_id));
        }
        Task::none()
    }

    fn view_window(&self, window_id: window::Id) -> Element<'_, Message> {
        let julep_id = match self.reverse_window_map.get(&window_id) {
            Some(id) => id,
            None => {
                return container(text("unknown window"))
                    .width(Fill)
                    .height(Fill)
                    .center(Fill)
                    .into();
            }
        };

        match self.core.tree.find_window(julep_id) {
            Some(window_node) => julep_core::widgets::render(
                window_node,
                &self.core.caches,
                &self.image_registry,
                &self.theme,
                &self.dispatcher,
            ),
            None => container(text("waiting for snapshot..."))
                .width(Fill)
                .height(Fill)
                .center(Fill)
                .into(),
        }
    }

    fn subscription(&self) -> Subscription<Message> {
        let mut subs = vec![
            Subscription::run(stdin_subscription).map(Message::Stdin),
            // Always listen for window close events so we can clean up maps.
            window::close_events().map(Message::WindowClosed),
        ];

        let has_on_event = self.core.active_subscriptions.contains_key("on_event");

        // -- Keyboard subscriptions --
        // When on_event is active, its catch-all listener already covers keyboard,
        // mouse, touch, and IME events. Skip specific subscriptions to avoid
        // duplicate event delivery (M-16).
        if !has_on_event && self.core.active_subscriptions.contains_key("on_key_press") {
            subs.push(event::listen_with(|evt, _status, _window| {
                if let iced::Event::Keyboard(iced::keyboard::Event::KeyPressed {
                    key,
                    modified_key,
                    physical_key,
                    location,
                    modifiers,
                    text,
                    repeat,
                }) = evt
                {
                    Some(Message::KeyPressed(KeyEventData {
                        key,
                        modified_key,
                        physical_key,
                        location,
                        modifiers,
                        text: text.map(|s| s.to_string()),
                        repeat,
                    }))
                } else {
                    None
                }
            }));
        }

        if !has_on_event
            && self
                .core
                .active_subscriptions
                .contains_key("on_key_release")
        {
            subs.push(event::listen_with(|evt, _status, _window| {
                if let iced::Event::Keyboard(iced::keyboard::Event::KeyReleased {
                    key,
                    modified_key,
                    physical_key,
                    location,
                    modifiers,
                }) = evt
                {
                    Some(Message::KeyReleased(KeyEventData {
                        key,
                        modified_key,
                        physical_key,
                        location,
                        modifiers,
                        text: None,
                        repeat: false,
                    }))
                } else {
                    None
                }
            }));
        }

        if !has_on_event
            && self
                .core
                .active_subscriptions
                .contains_key("on_modifiers_changed")
        {
            subs.push(event::listen_with(|evt, _status, _window| {
                if let iced::Event::Keyboard(iced::keyboard::Event::ModifiersChanged(mods)) = evt {
                    Some(Message::ModifiersChanged(mods))
                } else {
                    None
                }
            }));
        }

        // -- Mouse subscriptions --
        if !has_on_event && self.core.active_subscriptions.contains_key("on_mouse_move") {
            subs.push(event::listen_with(|evt, _status, window| match evt {
                iced::Event::Mouse(iced::mouse::Event::CursorMoved { position }) => {
                    Some(Message::CursorMoved(position, window))
                }
                iced::Event::Mouse(iced::mouse::Event::CursorEntered) => {
                    Some(Message::CursorEntered(window))
                }
                iced::Event::Mouse(iced::mouse::Event::CursorLeft) => {
                    Some(Message::CursorLeft(window))
                }
                _ => None,
            }));
        }

        if !has_on_event
            && self
                .core
                .active_subscriptions
                .contains_key("on_mouse_button")
        {
            subs.push(event::listen_with(|evt, _status, window| match evt {
                iced::Event::Mouse(iced::mouse::Event::ButtonPressed(button)) => {
                    Some(Message::MouseButtonPressed(button, window))
                }
                iced::Event::Mouse(iced::mouse::Event::ButtonReleased(button)) => {
                    Some(Message::MouseButtonReleased(button, window))
                }
                _ => None,
            }));
        }

        if !has_on_event
            && self
                .core
                .active_subscriptions
                .contains_key("on_mouse_scroll")
        {
            subs.push(event::listen_with(|evt, _status, window| {
                if let iced::Event::Mouse(iced::mouse::Event::WheelScrolled { delta }) = evt {
                    Some(Message::WheelScrolled(delta, window))
                } else {
                    None
                }
            }));
        }

        // -- Touch subscriptions --
        if !has_on_event && self.core.active_subscriptions.contains_key("on_touch") {
            subs.push(event::listen_with(|evt, _status, window| match evt {
                iced::Event::Touch(iced::touch::Event::FingerPressed { id, position }) => {
                    Some(Message::FingerPressed(id, position, window))
                }
                iced::Event::Touch(iced::touch::Event::FingerMoved { id, position }) => {
                    Some(Message::FingerMoved(id, position, window))
                }
                iced::Event::Touch(iced::touch::Event::FingerLifted { id, position }) => {
                    Some(Message::FingerLifted(id, position, window))
                }
                iced::Event::Touch(iced::touch::Event::FingerLost { id, position }) => {
                    Some(Message::FingerLost(id, position, window))
                }
                _ => None,
            }));
        }

        // -- IME subscriptions --
        if self.core.active_subscriptions.contains_key("on_ime") {
            subs.push(event::listen_with(|evt, _status, _window| match evt {
                iced::Event::InputMethod(iced::advanced::input_method::Event::Opened) => {
                    Some(Message::ImeOpened)
                }
                iced::Event::InputMethod(iced::advanced::input_method::Event::Preedit(
                    text,
                    cursor,
                )) => Some(Message::ImePreedit(text, cursor)),
                iced::Event::InputMethod(iced::advanced::input_method::Event::Commit(text)) => {
                    Some(Message::ImeCommit(text))
                }
                iced::Event::InputMethod(iced::advanced::input_method::Event::Closed) => {
                    Some(Message::ImeClosed)
                }
                _ => None,
            }));
        }

        // -- Window event subscriptions --
        if self
            .core
            .active_subscriptions
            .contains_key("on_window_event")
            || self.core.active_subscriptions.contains_key("on_file_drop")
            || self
                .core
                .active_subscriptions
                .contains_key("on_window_open")
            || self
                .core
                .active_subscriptions
                .contains_key("on_window_resize")
            || self
                .core
                .active_subscriptions
                .contains_key("on_window_focus")
            || self
                .core
                .active_subscriptions
                .contains_key("on_window_unfocus")
            || self
                .core
                .active_subscriptions
                .contains_key("on_window_move")
        {
            subs.push(window::events().map(|(id, evt)| Message::WindowEvent(id, evt)));
        }

        if self
            .core
            .active_subscriptions
            .contains_key("on_window_close")
        {
            subs.push(window::close_requests().map(Message::WindowCloseRequested));
        }

        // -- Animation frame subscription --
        if self
            .core
            .active_subscriptions
            .contains_key("on_animation_frame")
        {
            subs.push(window::frames().map(Message::AnimationFrame));
        }

        // Track system theme changes when theme follows system OR when subscribed
        if self.theme_follows_system
            || self
                .core
                .active_subscriptions
                .contains_key("on_theme_change")
        {
            subs.push(system::theme_changes().map(Message::ThemeChanged));
        }

        // -- Catch-all event subscription --
        // Subscribes to all keyboard, mouse, and touch events via a single
        // listener, re-using existing Message variants. Window events are
        // handled separately by on_window_event.
        //
        // To avoid duplicate event delivery when both on_event and a specific
        // subscription (e.g. on_key_press) are active, skip event categories
        // that already have a dedicated subscription listener above.
        if self.core.active_subscriptions.contains_key("on_event") {
            subs.push(event::listen_with(|evt, _status, window| match evt {
                // Keyboard
                iced::Event::Keyboard(iced::keyboard::Event::KeyPressed {
                    key,
                    modified_key,
                    physical_key,
                    location,
                    modifiers,
                    text,
                    repeat,
                }) => Some(Message::KeyPressed(KeyEventData {
                    key,
                    modified_key,
                    physical_key,
                    location,
                    modifiers,
                    text: text.map(|s| s.to_string()),
                    repeat,
                })),
                iced::Event::Keyboard(iced::keyboard::Event::KeyReleased {
                    key,
                    modified_key,
                    physical_key,
                    location,
                    modifiers,
                }) => Some(Message::KeyReleased(KeyEventData {
                    key,
                    modified_key,
                    physical_key,
                    location,
                    modifiers,
                    text: None,
                    repeat: false,
                })),
                iced::Event::Keyboard(iced::keyboard::Event::ModifiersChanged(mods)) => {
                    Some(Message::ModifiersChanged(mods))
                }
                // Mouse
                iced::Event::Mouse(iced::mouse::Event::CursorMoved { position }) => {
                    Some(Message::CursorMoved(position, window))
                }
                iced::Event::Mouse(iced::mouse::Event::CursorEntered) => {
                    Some(Message::CursorEntered(window))
                }
                iced::Event::Mouse(iced::mouse::Event::CursorLeft) => {
                    Some(Message::CursorLeft(window))
                }
                iced::Event::Mouse(iced::mouse::Event::ButtonPressed(button)) => {
                    Some(Message::MouseButtonPressed(button, window))
                }
                iced::Event::Mouse(iced::mouse::Event::ButtonReleased(button)) => {
                    Some(Message::MouseButtonReleased(button, window))
                }
                iced::Event::Mouse(iced::mouse::Event::WheelScrolled { delta }) => {
                    Some(Message::WheelScrolled(delta, window))
                }
                // Touch
                iced::Event::Touch(iced::touch::Event::FingerPressed { id, position }) => {
                    Some(Message::FingerPressed(id, position, window))
                }
                iced::Event::Touch(iced::touch::Event::FingerMoved { id, position }) => {
                    Some(Message::FingerMoved(id, position, window))
                }
                iced::Event::Touch(iced::touch::Event::FingerLifted { id, position }) => {
                    Some(Message::FingerLifted(id, position, window))
                }
                iced::Event::Touch(iced::touch::Event::FingerLost { id, position }) => {
                    Some(Message::FingerLost(id, position, window))
                }
                // IME
                iced::Event::InputMethod(iced::advanced::input_method::Event::Opened) => {
                    Some(Message::ImeOpened)
                }
                iced::Event::InputMethod(iced::advanced::input_method::Event::Preedit(
                    text,
                    cursor,
                )) => Some(Message::ImePreedit(text, cursor)),
                iced::Event::InputMethod(iced::advanced::input_method::Event::Commit(text)) => {
                    Some(Message::ImeCommit(text))
                }
                iced::Event::InputMethod(iced::advanced::input_method::Event::Closed) => {
                    Some(Message::ImeClosed)
                }
                // Window events handled by on_window_event
                _ => None,
            }));
        }

        Subscription::batch(subs)
    }

    fn apply(&mut self, message: IncomingMessage) {
        // Extension commands bypass the normal tree update / diff / patch cycle.
        match &message {
            IncomingMessage::ExtensionCommand {
                node_id,
                op,
                payload,
            } => {
                let events = self.dispatcher.handle_command(
                    node_id,
                    op,
                    payload,
                    &mut self.core.caches.extension,
                );
                for ev in events {
                    emit_event(ev);
                }
                return;
            }
            IncomingMessage::ExtensionCommandBatch { commands } => {
                for cmd in commands {
                    let events = self.dispatcher.handle_command(
                        &cmd.node_id,
                        &cmd.op,
                        &cmd.payload,
                        &mut self.core.caches.extension,
                    );
                    for ev in events {
                        emit_event(ev);
                    }
                }
                return;
            }
            _ => {}
        }

        let is_snapshot = matches!(message, IncomingMessage::Snapshot { .. });
        let is_tree_change = matches!(
            message,
            IncomingMessage::Snapshot { .. } | IncomingMessage::Patch { .. }
        );

        let effects = self.core.apply(message);
        for effect in effects {
            match effect {
                julep_core::engine::CoreEffect::SyncWindows => {
                    let task = self.sync_windows();
                    self.pending_tasks.push(task);
                }
                julep_core::engine::CoreEffect::EmitEvent(event) => emit_event(event),
                julep_core::engine::CoreEffect::EmitEffectResponse(response) => {
                    emit_effect_response(response)
                }
                julep_core::engine::CoreEffect::WidgetOp { op, payload } => {
                    let task = self.handle_widget_op(&op, &payload);
                    self.pending_tasks.push(task);
                }
                julep_core::engine::CoreEffect::WindowOp {
                    op,
                    window_id,
                    settings,
                } => {
                    let task = self.handle_window_op(&op, &window_id, &settings);
                    self.pending_tasks.push(task);
                }
                julep_core::engine::CoreEffect::ThemeChanged(theme) => {
                    self.theme = theme;
                    self.theme_follows_system = false;
                }
                julep_core::engine::CoreEffect::ThemeFollowsSystem => {
                    self.theme_follows_system = true;
                }
                julep_core::engine::CoreEffect::ImageOp {
                    op,
                    handle,
                    data,
                    pixels,
                    width,
                    height,
                } => {
                    self.handle_image_op(
                        &op,
                        &handle,
                        data.as_deref(),
                        pixels.as_deref(),
                        width,
                        height,
                    );
                }
                julep_core::engine::CoreEffect::ExtensionConfig(config) => {
                    self.dispatcher.init_all(&config);
                }
                julep_core::engine::CoreEffect::SpawnAsyncEffect {
                    request_id,
                    effect_type,
                    params,
                } => {
                    let task = Task::perform(
                        async move {
                            julep_core::effects::handle_async_effect(
                                request_id,
                                &effect_type,
                                &params,
                            )
                            .await
                        },
                        |response| {
                            emit_effect_response(response);
                            Message::NoOp
                        },
                    );
                    self.pending_tasks.push(task);
                }
            }
        }

        // After tree changes, update per-window theme cache and notify extensions.
        if is_tree_change {
            // Rebuild per-window theme cache from current tree.
            self.window_theme_cache.clear();
            for win_id in self.core.tree.window_ids() {
                // When resolve_theme_only returns None it means "system" --
                // no cache entry, falls through to the system_theme path
                // in theme_for_window().
                if let Some(node) = self.core.tree.find_window(&win_id)
                    && let Some(theme_val) = node.props.get("theme")
                    && let Some(theme) = julep_core::theming::resolve_theme_only(theme_val)
                {
                    self.window_theme_cache.insert(win_id, theme);
                }
            }

            if is_snapshot {
                self.dispatcher.clear_poisoned();
            }
            if let Some(root) = self.core.tree.root() {
                self.dispatcher
                    .prepare_all(root, &mut self.core.caches.extension, &self.theme);
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

pub(crate) fn run(builder: julep_core::app::JulepAppBuilder) -> iced::Result {
    let args: Vec<String> = std::env::args().collect();

    // Levelled logging via RUST_LOG. Default: warn (quiet). Use
    // RUST_LOG=julep=debug (or =info, =trace) for more output.
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("warn")).init();

    // Parse codec flags early so all modes (headless, test, normal) can use them.
    let forced_codec = if args.contains(&"--msgpack".to_string()) {
        Some(Codec::MsgPack)
    } else if args.contains(&"--json".to_string()) {
        Some(Codec::Json)
    } else {
        None
    };

    {
        if args.contains(&"--headless".to_string()) {
            crate::headless::headless_mode::run(forced_codec, builder.build_dispatcher());
            return Ok(());
        }
    }

    let test_mode = args.contains(&"--test".to_string());

    // Read the first message synchronously to get iced settings and font
    // data before the daemon starts. This must happen before the stdin
    // reader thread is spawned.
    let (initial_settings, iced_settings, font_bytes, reader) = read_initial_settings(forced_codec);

    // Send the hello handshake before any other output. The codec is set
    // inside read_initial_settings, so it's safe to emit framed messages now.
    emit_hello();

    // Spawn stdin reader thread with tokio channel. The receiver goes into
    // STDIN_RX so the subscription (which is a fn pointer, not a closure)
    // can take it once on first call.
    let (tx, rx) = tokio::sync::mpsc::channel::<StdinEvent>(64);
    spawn_stdin_reader(tx, reader);
    *STDIN_RX.lock().expect("STDIN_RX lock poisoned") = Some(rx);

    let settings_slot: Mutex<Option<(serde_json::Value, Vec<Vec<u8>>)>> =
        Mutex::new(Some((initial_settings, font_bytes)));
    let builder_slot: Mutex<Option<julep_core::app::JulepAppBuilder>> = Mutex::new(Some(builder));

    iced::daemon(
        move || {
            let (settings, fonts) = settings_slot
                .lock()
                .expect("settings_slot lock poisoned")
                .take()
                .unwrap_or_default();

            let dispatcher = builder_slot
                .lock()
                .expect("builder_slot lock poisoned")
                .take()
                .expect("daemon init closure called more than once")
                .build_dispatcher();
            let mut app = App::new(test_mode, dispatcher);

            // Extract scale_factor before applying settings to Core
            let sf = settings
                .get("scale_factor")
                .and_then(|v| v.as_f64())
                .map(|v| v as f32)
                .unwrap_or(1.0);
            app.scale_factor = if sf <= 0.0 || !sf.is_finite() {
                log::warn!("invalid initial scale_factor {sf}, using 1.0");
                1.0
            } else {
                sf
            };

            // Apply initial settings to Core (Settings doesn't produce effects)
            let _ = app.core.apply(IncomingMessage::Settings { settings });

            // Build font load tasks
            let font_tasks: Vec<Task<Message>> = fonts
                .into_iter()
                .map(|bytes| {
                    iced::font::load(bytes).map(|result| {
                        if let Err(e) = result {
                            log::error!("font load error: {e:?}");
                        }
                        Message::NoOp
                    })
                })
                .collect();

            let task = if font_tasks.is_empty() {
                Task::none()
            } else {
                Task::batch(font_tasks)
            };

            (app, task)
        },
        App::update,
        App::view_window,
    )
    .title(App::title_for_window)
    .subscription(App::subscription)
    .theme(App::theme_for_window)
    .scale_factor(App::scale_factor_for_window)
    .settings(iced_settings)
    .run()
}
